### ISSUE TITLE
Commit status checks are innacurrate

### ISSUE THREAD

**Issue by colinjfw** [deliverybot/roadmap#2]
This is mainly because it seems that GitHub actually omits certain `check_run` events from the UI. We look at all check runs and sometimes get a different picture of commit health.

**Comment by alizain** [comment]
Would you be able to show the omitted `check_run` events in your UI?

**Comment by colinjfw** [comment]
I _really_ wish GitHub would aggregate check_run's into the checks api :)

**Comment by colinjfw** [comment]
Pushed a fix for this. Will leave open for a few days to gather feedback here:
<img width="360" alt="Screen Shot 2019-12-16 at 8 24 54 AM" src="https://user-images.githubusercontent.com/10747761/70923947-9a965b80-1fdd-11ea-8a2f-855edff0eb19.png">
